// TASK
const TODO_TASK = 'TODO_TASK';
export const SNACK_BAR = `${TODO_TASK}/SNACK_BAR`;
export const GET_ALL_TASKS_REQUEST = `${TODO_TASK}/GET_ALL_TASKS_REQUEST`;
export const GET_ALL_TASKS_SUCCESS = `${TODO_TASK}/GET_ALL_TASKS_SUCCESS`;
export const GET_ALL_TASKS_FAILURE = `${TODO_TASK}/GET_ALL_TASKS_FAIL`;
export const GET_ALL_TAKS_OFFSET_REQUEST = `${TODO_TASK}/GET_ALL_TAKS_OFFSET_REQUEST`;
export const GET_ALL_TAKS_OFFSET_SUCCESS = `${TODO_TASK}/GET_ALL_TAKS_OFFSET_SUCCESS`;
export const GET_ALL_TAKS_OFFSET_FAILURE = `${TODO_TASK}/GET_ALL_TAKS_OFFSET_FAILURE`;
export const ADD_TASK_REQUEST = `${TODO_TASK}/ADD_TASK_REQUEST`;
export const ADD_TASK_SUCCESS = `${TODO_TASK}/ADD_TASK_SUCCESS`;
export const ADD_TASK_FAILURE = `${TODO_TASK}/ADD_TASK_FAILURE`;
export const DELETE_TASKS = `${TODO_TASK}/DELETE_TASKS`;
export const EDIT_TASK_REQUEST = `${TODO_TASK}/EDIT_TASK_REQUEST`;
export const EDIT_TASK_SUCESS = `${TODO_TASK}/EDIT_TASK_SUCESS`;
export const EDIT_TASK_FAILURE = `${TODO_TASK}/EDIT_TASK_FAILURE`;
export const GET_ONE_TASK_REQUEST = `${TODO_TASK}/GET_ONE_TASK_REQUEST`;
export const GET_ONE_TASK_SUCCESS = `${TODO_TASK}/GET_ONE_TASK_SUCCESS`;
export const GET_ONE_TASK_FAILURE = `${TODO_TASK}/GET_ONE_TASK_FAILURE`;
export const DELETE_TASKS_REQUEST = `${TODO_TASK}/DELETE_TASKS_REQUEST`;
export const DELETE_TASKS_SUCCESS = `${TODO_TASK}/DELETE_TASKS_SUCCESS`;
export const DELETE_TASKS_FAILURE = `${TODO_TASK}/DELETE_TASKS_FAILURE`;

// CATEGORY
export const GET_ALL_CATEGORIES_REQUEST = `${TODO_TASK}/GET_ALL_CATEGORIES_REQUEST`;
export const GET_ALL_CATEGORIES_SUCESS = `${TODO_TASK}/GET_ALL_CATEGORIES_SUCESS`;
export const GET_ALL_CATEGORIES_FAILURE = `${TODO_TASK}/GET_ALL_CATEGORIES_FAILURE`;
